class ReportGenerator:
    def generate(self, data):
        target = data["target_name"]
        analysis = data["analysis"]
        scores = data["scores"]
        verdict = data["verdict"]
        timestamp = data["timestamp"]
        
        def format_score(s):
            return str(s) if s is not None else "N/A"
            
        # Luxury Spatial Tech Report Template (High-Fidelity)
        report = f"""# 💎 QVPro Master Analysis: {target}
**Date:** {timestamp}
**Status:** {verdict}

---

## 1. Value Proposition & Market Alpha (Score: {format_score(scores['market'])})
{analysis['market']}

## 2. Product Architecture & Commercial Logic (Score: {format_score(scores['product'])})
{analysis['product']}

## 3. Real Competitor Engine: Comparison Matrix (Score: {format_score(scores['competitor'])})
{analysis['competitor']}

## 4. Financial Optics & Monetization Hacks (Score: {format_score(scores['financial'])})
{analysis['financial']}

## 5. Commercial Viability & ROI (Score: {format_score(scores['commercial'])})
{analysis['commercial']}

## 6. Growth, Viral Potential & Scaling (Score: {format_score(scores['growth'])})
{analysis['growth']}

## 7. Risk Mitigation & Tactical Outlook (Score: {format_score(scores['risks'])})
{analysis['risks']}

---

## 🏆 MASTER SCORECARD: {format_score(scores['overall'])} / 100
**FINAL VERDICT:** {verdict.upper()}

---

### 💳 Actions & Strategic Support
<div style="display: flex; gap: 10px; margin-bottom: 20px;">
  <a href="https://buy.stripe.com/eVq8wH7l9awV2kaboaaVa06" style="background: #008F68; color: white; padding: 10px 20px; text-decoration: none; border: 1px solid #E8E8E8; font-weight: bold;">🔓 Unlock Full 12-Page Deep Dive</a>
  <a href="https://buy.stripe.com/cNi8wH5d120pe2S9g2aVa01" style="background: #4B0082; color: white; padding: 10px 20px; text-decoration: none; border: 1px solid #E8E8E8; font-weight: bold;">🌟 Pro Subscription ($2/mo)</a>
</div>

**Affiliate Partner:** [QuantVantage MallFloor](https://quantvantage.ai/mall) - *Experience spatial commerce at the Premium Tool Bazaar.*

---
*Generated by QuantVantage AI Pro | Master Analysis Engine*
"""
        return report

